---
- name: Cleanup the previous iptables-restore systemd method
  import_tasks: cleanup.yml
  when: cleanup_iptables_restore_systemd

- name: Install iptables-persistent which ensures rules are applied at an appropriate stage during boot
  apt:
    name: iptables-persistent
    state: present

- name: Create /etc/iptables directory
  file:
    path: /etc/iptables
    state: directory
    owner: root
    group: root
    mode: 0700

- name: Update the /etc/iptables/rules.v4 file
  template:
    src: rules.v4.j2
    dest: /etc/iptables/rules.v4
    owner: root
    group: root
    mode: 0600
  register: iptables_config_v4_result
  notify:
    - Apply IPV4 rules

- name: Update the /etc/iptables/rules.v6 file
  template:
    src: rules.v6.j2
    dest: /etc/iptables/rules.v6
    owner: root
    group: root
    mode: 0600
  register: iptables_config_v6_result
  notify:
    - Apply IPV6 rules
